---

- name: Download node
  shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: Install awscli
  shell: pip3 install awscli --upgrade --user

- name: Install node
  apt:
    name: nodejs
    state: present

- name: Install slack
  command: snap install slack --classic

- name: Install spotify
  command: snap install spotify

- name: Install 1Password
  command: snap install 1password

- name: Install intelliJ
  command: snap install intellij-idea-ultimate --classic --edge

- name: Install pycharm
  command: snap install pycharm-community --classic

- name: Install postman
  command: snap install postman

- name: Install vscode
  command: snap install code --classic